### ISSUE TITLE
how do i test?

### ISSUE THREAD

**Issue by ralyodio** [eracknaphobia/plugin.video.mlbtv#2]
I made a minor change to your plugin, but when I zip it up and install from zip it fails.

What am I doing wrong?

**Comment by eracknaphobia** [comment]
Sometimes kodi needs to be restarted when updating addons, especially if you've done more than one update on a single addon. Other than that check your log file, it should tell you why the install failed.

**Comment by chovy** [comment]
It worked the 2nd time. I didn't see anything in error log.

On another note: is there anyway to get the feed for the 30fps master not the master_web60? The 60fps feeds are too choppy for me. I tried just changing the manifest file to filter for HTTP_WIRED_WEB instead of HTTP_WIRED_WEB60 but then I get `media content not found` error.

**Comment by eracknaphobia** [comment]
You can set the desired stream quality in the add-on settings screen under Visual > Stream Quality. 3500 and below are all 30fps

**Comment by chovy** [comment]
Is there any difference between getting the 1800k stream for HTTP_CLOUD_WIRED_60 vs. HTTP_CLOUD_WIRED? Both seem to work. I assume the HTTP_CLOUD_WIRED one is not 60fps.

**Comment by eracknaphobia** [comment]
Nope, they are exactly the same. The only stream that is 60fps is the 5000k stream. All others are 30fps. If you hit the "O" key while watching a stream you will see the fps at the top of the stream to verify this.
